server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

cloud:
  sample:
    msg: hello

management:
  endpoint:
    shutdown:
      enabled: true
    restart:
      enabled: true
