server:
  port: 8079

spring:
  application:
    name: configcenter
  rabbitmq:
    addresses: localhost:5672
    username: fanlei
    password: fanlei
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

